version: "3"
services: 
  #create a name for the intial service (the initial container)
  react-app:
    # specify the image or docker file we're going to use
    # to create this initial container
    # note: before we used build ., but that meant we had a dockerfile,
    # now we have a dockerfile.dev
    # instead of . we'll use context: .
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment: 
      - CHOKIDAR_USEPOLLING=true
    # specify the ports - is for lists in yml
    # first is 3000 outside of the container, to port 3000 inside our
    # container
    ports:
      - "3000:3000"
      # here's where we can shorthand our volume cmd
    volumes: 
      # this means don't try to map a folder up against app/node_modules
      - /app/node_modules
      # instead we're going to create the map from . folder outside of 
      # the container, to /app inside the container
      - .:/app